baseURL = 'https://maddiespaddies.com/'
languageCode = 'en-us'
title = 'steinburgers ğŸ”'
subtitle = "ramblings of a sane man"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
